# Generated by Django 5.2.8 on 2025-11-27 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=255)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.BigIntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('order_status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('failed', 'failed'), ('reverse', 'reverse')], default='Pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('paypal', 'paypal'), ('transfer', 'transfer')], default='paystack', max_length=255)),
                ('payment_completed', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('discount_price', models.BigIntegerField(blank=True, null=True)),
                ('main_photo', models.ImageField(upload_to='product')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo9', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo10', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('in_stock', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50)),
                ('color', models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('pink', 'pink')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.collection')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
    ]
